services:
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container

  productservice:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "8081:80"  # Map port 8081 on the host to port 80 in the container
